{{- if .Values.ingress.rewriteTarget }}
# Replace path with regex
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "app.chartname" . }}-replacepathregex
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replacePathRegex:
    regex: {{ .Values.ingress.rewriteTarget.regex }}
    replacement: {{ .Values.ingress.rewriteTarget.replacement }}
{{- end }}
{{- if .Values.ingress.headers }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "app.chartname" . }}-headers
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  headers:
{{ toYaml .Values.ingress.headers | indent 4 }}
{{- end }}
{{- if .Values.ingress.clientMaxBodySize }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "app.chartname" . }}-client-max-body-size
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  buffering:
    maxRequestBodyBytes: {{ .Values.ingress.clientMaxBodySize }}
{{- end }}