apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.chartname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: http
      targetPort: {{ .Values.service.targetPort }}
      port: {{ .Values.service.port }}
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
